repos:
  - repo: local
    hooks:
      - id: biome-check
        name: Biome (lint + format)
        entry: biome
        language: system
        args: [check, --apply]
        types_or: [javascript, jsx, ts, tsx, json]

      - id: biome-format
        name: Biome (format)
        entry: biome
        language: system
        args: [format, --write]
        types_or: [javascript, jsx, ts, tsx, json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: unit-tests
        name: Unit Tests
        entry: npm
        language: system
        args: [test]
        pass_filenames: false
        always_run: true
